version: "3.8"
name: fashionista-valentine-portal

services:
  db:
    image: supabase/postgres:15.1.0.117
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fashionista_dev

  supabase:
    image: supabase/supabase-local:latest
    ports:
      - "54321:8000"
    environment:
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: local-development-secret
      STUDIO_PORT: 3000
      API_EXTERNAL_URL: http://localhost:54321
      KONG_URL: http://kong:8000
      SUPABASE_URL: http://localhost:54321
      SUPABASE_ANON_KEY: dummy-key-for-development
      SUPABASE_SERVICE_ROLE_KEY: dummy-service-key-for-development
    depends_on:
      - db

volumes:
  postgres_data:
  storage_data: 