name: Test Supabase Secrets

on:
  workflow_dispatch:  # This allows manual trigger of the workflow

jobs:
  test-secrets:
    name: 🔑 Test Secrets
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Test Supabase Connection
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Testing Supabase connection..."
          node -e '
          const { createClient } = require("@supabase/supabase-js");
          
          async function testConnection() {
            const supabase = createClient(
              process.env.SUPABASE_URL,
              process.env.SUPABASE_KEY
            );
            
            try {
              const { data, error } = await supabase.from("events").select("count");
              if (error) throw error;
              console.log("✅ Supabase connection successful!");
              console.log(`Found ${data.length} events in database`);
            } catch (error) {
              console.error("❌ Supabase connection failed:", error.message);
              process.exit(1);
            }
          }
          
          testConnection();
          ' 